### ISSUE TITLE
Scanning for multiple devices simultaneously using the ".is" class method 

### ISSUE THREAD

**Issue by raykamp** [sandeepmistry/noble-device#3]
Hey Sandeep, great work on this project and noble. It's been a huge help to the BLE community! 

As a bit of context.. I'm developing a node-red node for the Light Blue Bean and I'm using Jacob Rosenthal's Ble-Bean project. 

I'm looking to use Noble-device to scan for multiple devices of the "Bean" type simultaneously. The current mechanism for searching for a unique device appears to be defining the "if" method of the "Bean" (Noble-device) class. This works great when I'm looking for only one device at a time, but doesn't support the use case of uniquely searching for multiple devices at once. 

Here's a snippet of my code. I have something like a "bean manager" instance that is calling this code before it attempts to discover it's associated Bean. 

```
bleBean.is = function(peripheral){
    return ( peripheral.advertisement.localName === this.name || peripheral.uuid === this.uuid );
}.bind(this);
```

Any support/help/suggestions that you have are much appreciated

**Comment by marcnicholas** [comment]
:+1:  for the usefulness of this feature!

**Comment by sandeepmistry** [comment]
@raykamp discover is designed to only discover one of the "noble device" type. Mainly because I usually only have one of each device to test with.

Just to clarify, you want to scan for all beans? (I'm confused by the local name, uuid checks in the code snippet)

How about the following API's?

 * ``discoverOne``
  * discovers a single device, stops scanning
 * ``discoverAll``
  * discovers all devices
 * ``discoverByUuid`` 
   * discovers a single device by uuid, the stops scanning

Maybe an additional call to stop ``discoverAll`` as well.

**Comment by raykamp** [comment]
@sandeepmistry, thank you for the prompt reply. 

Your proposed "discoverAll" feature would be very useful, but what the purpose of this particular issue was for simultaneously scanning for multiple Beans at once and identifying each individually by their advertising data contents.
For example, submitting two concurrent requests to noble-device for the discovery of a bean named "<b>Bean_A</b>" and another named "<b>Bean_B</b>"

I've forked your repo and have made a change to the discover routine in util.js. This change seems to allow enable multiple concurrent discovery requests by adding an "isPeripheral" function parameter to the  discover routine. This takes the place of the class method ".is" 

Please let me know what you think of the change/concept. If you like the concept, I can clean it up an make a PR. 

https://github.com/raykamp/noble-device/commit/54dcc38c606b29a9bd6c051cae26c7696f4f736d

**Comment by sandeepmistry** [comment]
@raykamp I'm liking the ``discoverRequests`` counter concept. Keep in mind if more than one module is using noble, and ``stopScanning`` is called, all scans are stopped - we can defer solving this.

The ``.is`` message would still be needed for other devices like the TI Sensortag, that don't advertise a service UUID that can be used to filter. So, let's leave it in, and the Bean module continue to not use it.

Potential API:

 * ``discoverAll(callback)``
 * ``stopDiscover(discoverAllCallback)``
  * removes the ``discoverAllCallback`` from ``discoverAll`` and stops scanning if no requests pending
 * ``discover(callback)``
  * same behaviour as now, but delegates to ``discoverAll`` and call ``stopDiscover`` once a device has been found
 * ``discoverWithFilter(filter, callback)``
  * same as discover, but with a filter function

**Comment by raykamp** [comment]
@sandeepmistry, your proposed API looks good to me

**Comment by marcnicholas** [comment]
:+1:

**Comment by sandeepmistry** [comment]
@raykamp @marcnicholas please try out the latest commit.

One note, the ``filter`` argument of ``discoverWithFilter`` takes the ``NobleDevice`` "type" as an argument instead of the raw noble peripheral.

The ``NobleDevice`` [constructor already assigns the ``uuid`` as a property](https://github.com/sandeepmistry/noble-device/blob/master/lib/noble-device.js#L12). For the ``Bean`` constructor I would recommend you add the following line:

```javascript
var Bean = function(peripheral) {
  // ...
  
  this.name = peripheral.advertisement.localName;
};
```

Then the call in the example you provided would look like:

```javascript
Bean.discoverWithFilter(function(bean) {
  return (bean.name === 'Bean_A');
}, onBeanADiscover);

Bean.discoverWithFilter(function(bean) {
  return (bean.name === 'Bean_B');
}, onBeanBDiscover);
```

If things look good, we can close the issue, then update the docs, and I can publish a new version to npm.

**Comment by raykamp** [comment]
Hi @sandeepmistry , I've tested the code and it is working well so far. I've mainly tested "discoverWithFilter".

**Comment by sandeepmistry** [comment]
@raykamp @marcnicholas version ``0.1.1`` has been published to npm with the new discover API's discussed above.

**Comment by marcnicholas** [comment]
w00t :)
